language: ruby

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=5
    - VIPS_VERSION_MICRO=7
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libfftw3-dev
      - libglib2.0-dev

cache:
  directories:
    - $HOME/vips

before_install:
  - uname -a
  - bash install-vips.sh --without-python

rvm:
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/ruby_vips_1.0.gemfile
  - gemfiles/ruby_vips_2.0.gemfile

script: "bundle exec rspec spec/"

